theme: jekyll-theme-slate
title: Welcome to My homepage
description: I am a PhD student in Arizona State University. I am advised by  Dr. Pavan Turaga https://pavanturaga.com/  My broad research area is in Computer Vision. I am interested in Topological Data Analysis, Differential Geometry, Optimal Transport and generative models all with their applications to Computer Vision. 
