plugins:
  - jekyll-seo-tag
theme: jekyll-theme-slate
title: Kowshik Thopalli
description: I am a first year PhD student in Arizona State University. I am advised by  Dr. Pavan Turaga. 
author : Kowshik Thopalli
github_username: kowshikthopalli
baseurl: ""
url: "http://kowshikthopalli.github.io"

markdown: kramdown
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

twitter:
  username: kowshik0808
social:
  name: Kowshik Thopalli
  links:
    - https://www.linkedin.com/in/kowshik-thopalli-281bb255
    - https://twitter.com/kowshik0808
    - https://github.com/kowshikthopalli
  
